on:
  workflow_call:
    inputs:
      runs-on:
        description: The Platform to execute on
        type: string
        default: self-hosted
      directory:
        description: The terraform plan output directory
        type: string
        default: .
        required: false
      # severity:
      #   description: The severities to output
      #   type: string
      #   default: "CRITICAL"
        # required: false
      soft-fail:
        description: Toggle scan failure if vulnerabilities are found
        type: boolean
        default: false
        required: false
      skip-dirs:
        description: Comma separated list of directories where traversal is skipped
        type: string
        required: false
      timeout:
        description: "timeout (default 5m0s)"
        type: string
        required: false
        default: "5m0s"

jobs:
  checkov-scan:
    name: "Trigger Checkov Scan"
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Scan IaC
        uses: bridgecrewio/checkov-action@master
        with:
          # scanners: "vuln,misconfig"
          framework: terraform
          directory: ${{ inputs.directory }}
          # severity: ${{ inputs.severity }}
          soft-fail: ${{ inputs.soft-fail }}
          timeout: ${{ inputs.timeout }}

  slack-alert:
    if: failure()
    needs: checkov-scan
    runs-on: ${{ inputs.runs-on }}
    continue-on-error: true
    steps:
      - name: Trigger Slack Notification
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
          SLACK_CHANNEL: github-security-alerts
          SLACK_COLOR: ${{ needs.checkov-scan.result }}
          SLACK_MESSAGE: ":hammer_and_wrench: Checkov Scanner detected security misconfigurations."
          SLACK_TITLE: Information
          SLACK_FOOTER: Powered by Yassir Security Team
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
