on:
  workflow_call:
    inputs:
      runs-on:
        description: The Platform to execute on
        type: string
        default: self-hosted
      directory:
        description: The terraform plan output directory
        type: string
        required: true

jobs:
  iac-scan:
    name: "Trigger Checkov Audit"
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Scan IAC
        uses: bridgecrewio/checkov-action@master
        with:
          directory: {{ inputs.directory }}
          framework: terraform