on:
  workflow_call:
    inputs:
      runs-on:
        description: The Platform to execute on
        type: string
        default: self-hosted

jobs:
  mobile-scan:
    name: "Trigger Mobile App Audit"
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Audit code
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload audit report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif