on:
  workflow_call:
    inputs:
      runs-on:
        description: The Platform to execute on
        type: string
        default: self-hosted
      directory:
        description: The terraform plan output directory
        type: string
        default: .
        required: true
      severity:
        description: The severities to output
        type: string
        default: 'MEDIUM,HIGH,CRITICAL'
        required: true

jobs:
  trivy-scan:
    name: "Trigger Trivy Scan"
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Scan OSS
        uses: aquasecurity/trivy-action@0.17.0
        with:
          scanners: 'vuln,misconfig'
          scan-type: 'repo'
          scan-ref: .
          severity: ${{ inputs.severity }}