on:
  workflow_call:
    inputs:
      runs-on:
        description: The Platform to execute on
        type: string
        default: linux-iac
      iac_type:
        description: "IaC Type (default terraform)"
        type: string
        required: false
        default: "terraform"

jobs:
  terrascan:
    runs-on: ${{ inputs.runs-on }}
    name: "Terrascan"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@v1.4.1
      with:
        iac_type: ${{ inputs.iac_type }}
        only_warn: false
        find_vulnerabilities: true
  slack-alert:
    if: failure()
    needs: terrascan
    runs-on: ${{ inputs.runs-on }}
    continue-on-error: true
    steps:
      - name: Trigger Slack Notification
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
          SLACK_CHANNEL: github-security-alerts
          SLACK_COLOR: ${{ needs.terrascan.result }}
          SLACK_MESSAGE: ":hammer_and_wrench: Terrascan detected security issues."
          SLACK_TITLE: Information
          SLACK_FOOTER: Powered by Yassir Security Team
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
